server {
  listen       8080;
  server_name  _;
  root   /public;

  location ~* (([^\/]+).*\.(css|js|gif|jpe?g|png|svg))$ {
    try_files /$1 =404;
  }

  location / {
      index  index.html index.htm;
      error_page 404  =200 /index.html;
  }

  location /health {
      root /dev/null;
      access_log off;
      return 200 "healthy";
      add_header Content-Type text/plain;
  }

  # favicon.ico
  location = /favicon.ico {
      log_not_found off;
      access_log    off;
  }

  add_header Content-Security-Policy "frame-ancestors https://apps.mypurecloud.jp";
}
